# Generated by Django 6.0.2 on 2026-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_idx_user_type_user_idx_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('lab_tech', 'Lab Technician')], default='patient', max_length=10),
        ),
    ]
