# Generated by Django 6.0.2 on 2026-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_patient'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['is_active'], name='idx_med_active'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='medication_end_after_start'),
        ),
    ]
