# Generated by Django 6.0.2 on 2026-02-07 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g. "Twice daily"', max_length=100)),
                ('duration', models.CharField(blank=True, default='', help_text='e.g. "7 days"', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('diagnosis', models.JSONField(blank=True, default=list, help_text='List of diagnoses')),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptoms')),
                ('examination_notes', models.TextField(blank=True, default='')),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('vitals', models.JSONField(blank=True, default=dict, help_text='e.g. {"blood_pressure": "120/80", "heart_rate": 72, "temperature": 98.6}')),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
