# Generated by Django 6.0.2 on 2026-02-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('medical', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='appointments.appointment'),
        ),
    ]
