# Generated by Django 6.0.2 on 2026-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_idx_appointment_status_and_more'),
        ('medical', '0004_alter_medicalrecord_doctor_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['-created_at'], name='idx_medrec_created'),
        ),
    ]
