# Generated by Django 6.0.2 on 2026-02-07 05:57

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('document_type', models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('insurance', 'Insurance'), ('ecg', 'ECG'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
