# Generated by Django 6.0.2 on 2026-02-07 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_medicaldocument_patient'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['document_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['-created_at'], name='idx_doc_created'),
        ),
    ]
