# Generated by Django 6.0.2 on 2026-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remap_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('insurance', 'Insurance'), ('referral_letter', 'Referral Letter'), ('vaccination_record', 'Vaccination Record'), ('medical_history', 'Medical History'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
