# Generated by Django 6.0.2 on 2026-02-08 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_idx_appointment_status_and_more'),
        ('users', '0003_alter_user_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_category', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('imaging', 'Imaging'), ('cardiac', 'Cardiac'), ('pathology', 'Pathology'), ('microbiology', 'Microbiology'), ('other', 'Other')], default='blood', max_length=15)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('results_available', 'Results Available'), ('reviewed', 'Reviewed')], default='ordered', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests_ordered', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='users.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_reviewed', to='users.doctor')),
            ],
            options={
                'db_table': 'lab_tests',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField(help_text='Primary result value or summary')),
                ('reference_range', models.CharField(blank=True, default='', help_text='e.g. "70-100 mg/dL"', max_length=100)),
                ('unit', models.CharField(blank=True, default='', help_text='e.g. "mg/dL", "mmol/L"', max_length=50)),
                ('interpretation', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('result_file', models.FileField(blank=True, help_text='Uploaded result document (PDF, image, etc.)', null=True, upload_to='lab_results/')),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab_tests.labtest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_test_results',
            },
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['-ordered_at'], name='idx_labtest_ordered'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status'], name='idx_labtest_status'),
        ),
    ]
