# Generated by Django 6.0.2 on 2026-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='findings',
            field=models.TextField(blank=True, default='', help_text='Detailed narrative findings (imaging/pathology reports)'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='impression',
            field=models.TextField(blank=True, default='', help_text='Summary conclusion / diagnostic impression'),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='result_value',
            field=models.TextField(blank=True, default='', help_text='Primary result value or summary (structured tests)'),
        ),
    ]
